ynquiz_website/quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('play/', views.play, name='play'),
    path('ranking/', views.ranking, name='ranking'),
    path('signin/', views.signin, name='signin'),
    path('contact/', views.contact, name='contact')
]

ynquiz_website/ynquiz_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('', TemplateView.as_view(template_name='homeco.html'), name='homeco'),
    path('', include('quiz.urls')),
]

ynquiz_website/quiz/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    school_field = models.CharField(max_length=100)
    score = models.IntegerField(default=0)
    is_student = models.BooleanField('student status', default=True)
    is_teacher = models.BooleanField('teacher status', default=False)
    
class Question (models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    question_content = models.CharField(max_length=500)

    class Meta:
        verbose_name = "question"

    def __str__(self):
        return self.question_content

class Answer (models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=100)
    is_correct = models.BooleanField('correct answer', default=False)

    class Meta:
        verbose_name = "réponse"

    def __str__(self):
        return self.answer_text
    

ynquiz_website/quiz/forms.py
from django import forms
from .models import User

class QuizForm(forms.Form):
   
    choice_field = forms.ChoiceField(label='', widget=forms.RadioSelect)
    answerID = ''


class UserCreationForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('is_student','is_teacher')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('is_student','is_teacher','score')

ynquiz_website/quiz/views.py
from django.http import HttpResponse
from django.shortcuts import render
from quiz.models import Answer
from quiz.models import Question
from random import seed
from random import randint 
from django.http import HttpResponseRedirect
from quiz.forms import QuizForm
from django.http import JsonResponse
from quiz.models import User

def home(request):
    return render(request, 'quiz/home.html', locals())

def play(request):

    #If we handle the page after POST (ie: after we validate the answer)
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = QuizForm(request.POST)
        #We take the question ID from the JavaScript getAnswer() function
        questionID = request.POST['questionID']
        #We take the answer ID from the JavaScript getAnswer() function
        answerID = request.POST['answerID']
        #We take all the answer from the question
        answers = Answer.objects.filter(question__id=questionID)
         #We take the ID of the good answer
        for i in range(0,answers.count()):
            if(answers[i].is_correct == True):
                goodAnswerID = i

        #If the answer selected by the user is right...
        if True == answers[int(answerID)].is_correct : 
        #We set the boolean to True
            goodAnswerBool = True

            print("score : ")
            print(request.user.score)
            print("new score:")
            request.user.score += 10
            print(request.user.score)
            request.user.save()
            
        #We set the boolean to False
        else:
            goodAnswerBool = False

            print("score : ")
            print(request.user.score)
            print("score : ")
            print(request.user.score)
            print("new score:")
            request.user.score += -5
            print(request.user.score)
            request.user.save()
        
        data = {
            'goodAnswerBool': goodAnswerBool,
            'goodAnswerID': goodAnswerID,
        }
        theReturn = JsonResponse(data)
        
    # If this is a GET (or any other method) create the default form.
    else:
        #Initiate the random        
        seed()
        #We take a question randomly
        questionID = randint(1,Question.objects.all().count())
        #We take all the answers possible
        answers = Answer.objects.filter(question__id=questionID)
        #We take the question
        question = Question.objects.filter(id=questionID)
        #Array of the iteration to random the answer
        keys = []
        #Array of answers randomed
        answersArray = []
        #Array to stock the answer temporaly
        anAnswer = []
        #We create a form (not used anymore)
        form = QuizForm(request.POST or None)
        #We randomise all the answers and put i in a format to be understand by the form
        for i in range(0,3) : 
            while True:
                key = randint(0,2)
                if ((key in keys) == False) :
                    keys.append(key)
                    anAnswer.append(key)
                    anAnswer.append(answers[key].answer_text)
                    answersArray.append(tuple(anAnswer))
                    anAnswer = []
                    #We handle the ID of the correct answer
                    if(answers[key].is_correct == True):
                        goodAnswer = key
                    break
        #We put the randomised answers in the form
        form.fields['choice_field'].choices = answersArray
        #We put the good answer ID in the form 
        form.answerID = goodAnswer
        #Set up of the data set send at the HTML page when it's loading
        context = {
            'form' : form,
            'question': question[0],
            'questionID': questionID,
            'answerArray': answersArray,
        }
        theReturn = render(request, 'quiz/play.html', context )
    return theReturn

def ranking(request):
    users = User.objects.filter(is_student=True).order_by('-score')
    return render(request, 'quiz/ranking.html', locals())

def signin(request):
    return render(request, 'quiz/signin.html', locals())

def contact(request):
    # Construire le formulaire, soit avec les données postées,
    # soit vide si l'utilisateur accède pour la première fois
    # à la page.
    form = ContactForm(request.POST or None)
    # Nous vérifions que les données envoyées sont valides
    # Cette méthode renvoie False s'il n'y a pas de données 
    # dans le formulaire ou qu'il contient des erreurs.
    if form.is_valid(): 
        # Ici nous pouvons traiter les données du formulaire
        sujet = form.cleaned_data['sujet']
        message = form.cleaned_data['message']
        envoyeur = form.cleaned_data['envoyeur']
        renvoi = form.cleaned_data['renvoi']
        moui = form.cleaned_data['oui']

        # Nous pourrions ici envoyer l'e-mail grâce aux données 
        # que nous venons de récupérer
        envoi = True
    
    # Quoiqu'il arrive, on affiche la page du formulaire.
    return render(request, 'quiz/contact.html', locals())

ynquiz_website/quiz/templates/quiz/contact.html
{% if envoi %}Votre message a bien été envoyé !{% endif %}

<form action="{% url "contact" %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

ynquiz_website/quiz/templates/quiz/header.html
{% load static %}
<header>
    <a href="{% url "home" %}">
        <img
            src="{% static 'img/ynquiz_logo.svg' %}"
            alt="logo ynQuiz"
            width="50px"
            height="50px" />
        <h1>ynQuiz</h1>
    </a>
    <span onclick="toggleNav()">≡</span>
</header>

ynquiz_website/quiz/templates/quiz/home.html
{% extends "base.html" %}
{% block title %}ynQuiz - Accueil{% endblock %}
{% block header %}
{% include 'quiz/header.html' %}
{% endblock %}
{% block nav %}
{% include 'quiz/nav.html' %}
{% endblock %}
{% block content %}

{% if user.is_authenticated %}
        Bienvenue {{ user.username }}
{% else %}
        <p>Vous n'êtes pas connecté</p>
{% endif %}

<h2>Menu principal</h2>
<ul>
    <li><a href="{% url "play" %}">Jouer à ynQuiz</a></li>
    <li><a href="{% url "ranking" %}">Classement</a></li>
    {% if request.user.is_superuser %}
    <li><a href="{% url "admin:index" %}">Administration</a></li>
    {% endif %}
</ul>
{% endblock %}

ynquiz_website/quiz/templates/quiz/nav.html
<div id="sideMenu">
<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
<a href="{% url "home" %}">Accueil</a>
{% if user.is_authenticated %}
            <a href="{% url "logout" %}">Déconnexion</a>
{% else %}
        <a href="{% url "login" %}">Connexion</a>
{% endif %}
</div>
    
    

ynquiz_website/quiz/templates/quiz/play.html
{% extends "base.html" %}
{% block title %}ynQuiz - Jouer{% endblock %}
{% block header %}
{% include 'quiz/header.html' %}
{% endblock %}
{% block nav %}
{% include 'quiz/nav.html' %}
{% endblock %}
{% block content %}

<h3>{{ question.question_content }}</h3>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        <ul id="id_choice_field">
            <li>
                <input type="radio" name="choice_field" value={{answerArray.0.0}} required="" id="id_choice_field_{{answerArray.0.0}}" onClick="buttonAllowed('validate')" >
                <label for="id_choice_field_{{answerArray.0.0}}">
                 {{answerArray.0.1}}</label>

            </li>
            <li>
                <input type="radio" name="choice_field" value={{answerArray.1.0}} required="" id="id_choice_field_{{answerArray.1.0}}" onClick="buttonAllowed('validate')">
                <label for="id_choice_field_{{answerArray.1.0}}">
                {{answerArray.1.1}}</label>
        
            </li>
            <li>
                <input type="radio" name="choice_field" value={{answerArray.2.0}} required="" id="id_choice_field_{{answerArray.2.0}}" onClick="buttonAllowed('validate')">
                <label for="id_choice_field_{{answerArray.2.0}}">
                {{answerArray.2.1}}</label>
            </li>
        </ul>
        </table>
        <div id="answerDisplay" >
             
        </div>
        <script type="text/javascript"> var questID = {{ questionID }} </script>
        <button id="validateButton" type="button" onclick="getAnswer(questID)">Valider</button> <br>
        <button id="continueButton" type="button" onClick="window.location.reload();">Continuer</button>
    
        
    </form>

{% endblock %}

ynquiz_website/quiz/templates/quiz/ranking.html
{% extends "base.html" %}
{% block title %}ynQuiz - Classement{% endblock %}
{% block header %}
{% include 'quiz/header.html' %}
{% endblock %}
{% block nav %}
{% include 'quiz/nav.html' %}
{% endblock %}
{% block content %}
<h2>Classement</h2>
<table>
    <tr>
        <th scope="col" class="side_column">Position</th>
        <th scope="col">Nom d'utilisateur</th>
        <th scope="col" class="side_column">Score</th>
    </tr>
{% for user in users %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ user.username }}</td>
        <td>{{ user.score }}</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

ynquiz_website/quiz/templates/quiz/signin.html
{% extends "base.html" %}
{% block title %}ynQuiz - Connexion{% endblock %}
{% block header %}
{% include 'quiz/header.html' %}
{% endblock %}
{% block nav %}
{% include 'quiz/nav.html' %}
{% endblock %}
{% block content %}
<h2>Connexion</h2>
<p>Ceci est la page de connexion pour ynQuiz.</p>
{% endblock %}

ynquiz_website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'css/ynquiz.css' %}"/>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <title>{% block title %}ynQuiz{% endblock %}</title>
        <script type="text/javascript" src="{% static 'js/sidemenu.js' %}"></script>
    </head>
    <body>
        {% block header %}
        {% endblock %}
        <nav>
            {% block nav %}
            {% endblock %}
        </nav>
        <section id="content">
            {% block content %}{% endblock %}
        </section>
        <footer>&copy; ynQuiz 2019</footer>
    </body>
</html>